spring:
  # DataSource Config
  datasource:
    write:
      url: jdbc:mysql://118.25.77.78:3306/client_service?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
      username: root
      password: 1010521t
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      show-sql: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      # 合并多个DruidDataSource的监控数据
      #spring.datasource.useGlobalDataSourceStat=true
    read:
      show-sql: true
      url: jdbc:mysql://118.25.77.78:3306/client_service?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
      username: root
      password: 1010521t
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      initial-size: 1
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      # 合并多个DruidDataSource的监控数据
      #spring.datasource.useGlobalDataSourceStat=true
  redis:
    database: 2
    host:  192.168.212.128
    #password: # Login password of the redis server.
    port: 6379
    timeout: 0
    password:
  jedis:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 5
      min-idle: 0
  timeout: 10000

  rabbitmq:
    host: 192.168.212.128
    port: 5672
    username: admin
    password: admin
    virtualHost: /
  mail:
    host: xxx
    port: 25
    username: aaa@xxx.com
    password: xxx
    testConnection: false
server:
  port: 8089

mapper:
    mappers:
      - tk.mybatis.mapper.common.Mapper
    notEmpty: true

logging:
  level:
    com.innovation.emall.system.provider.mapper: DEBUG